version: '3'

volumes:
  pg_data_foodgrams:
  static_volume:
  media_volume:

services:
  db:
    container_name: db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_foodgram:/var/lib/postgresql/data
  backend:
    container_name: backend_prod
    image: helegven/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media
    depends_on: 
      - db
  frontend:
    container_name: frontend_prod
    image: helegven/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
    depends_on: 
      - backend
  gateway:
    container_name: nginx_prod
    image: helegven/foodgram_gateway
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/media
    ports:
      - 8000:80
    depends_on: 
      - frontend