# Generated by Django 2.2.28 on 2023-07-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingridients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
    ]
